name: Release
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

jobs:
  GetVersion:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      version: ${{ steps.version.outputs.value }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: version
        name: Get version
        run: echo "::set-output name=value::$(cat VERSION | grep v)"

  Github-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - GetVersion
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print version with needs
        run: echo ${{ needs.GetVersion.outputs.version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.GetVersion.outputs.version }}
          release_name: Release ${{ needs.GetVersion.outputs.version }}
          draft: false
          prerelease: false

  Deploy-Built-Artifacts:
    strategy:
      matrix:
        package:
          # Base packages
          - coingecko,coingecko.defiwrapper.eth
          - core-sdk-interface,interface.defiwrapper.eth
          - core-sdk,sdk.defiwrapper.eth

          # Token Resolvers
          - token-resolver-interface,interface.token.resolvers.defiwrapper.eth
          - ethereum-token-resolver,ethereum.token.resolvers.defiwrapper.eth

          # Account Resolvers
          - account-resolver-interface,interface.account.resolvers.defiwrapper.eth
          - covalent-account-resolver,covalent.account.resolvers.defiwrapper.eth

          # Price Resolvers
          - price-resolver-interface,interface.price.resolvers.defiwrapper.eth
          - coingecko-price-resolver,coingecko.price.resolvers.defiwrapper.eth

          # Protocol Resolvers
          - protocol-resolver-interface,interface.protocol.resolvers.defiwrapper.eth
          - ethereum-protocol-resolver,ethereum.protocol.resolvers.defiwrapper.eth

          # Asset Resolvers
          - asset-resolver-interface,interface.asset.resolvers.defiwrapper.eth
          - 1inch-asset-resolver,1inch.asset.resolvers.defiwrapper.eth
          - aave-asset-resolver,aave.asset.resolvers.defiwrapper.eth
          - compound-asset-resolver,compound.asset.resolvers.defiwrapper.eth
          - cream-asset-resolver,cream.asset.resolvers.defiwrapper.eth
          - curve-asset-resolver,curve.asset.resolvers.defiwrapper.eth
          - linkswap-asset-resolver,linkswap.asset.resolvers.defiwrapper.eth
          - sushi-asset-resolver,sushi.asset.resolvers.defiwrapper.eth
          - uniswap-asset-resolver,uniswap.asset.resolvers.defiwrapper.eth
          - yearn-asset-resolver,yearn.asset.resolvers.defiwrapper.eth

    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CI: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-deployments-v1
          restore-keys: |
            ${{ runner.os }}-yarn-deployments-

      # Install packages
      - name: Install pinata cli
        run: yarn global add pinata-upload-cli
      - name: Install ethers cli
        run: yarn global add @ethersproject/cli

      # Get Package Metadata
      - id: package
        name: Get Package Metadata
        run: |
          echo ::set-output name=name::$(node ./scripts/release/getPackageData.js ${{ matrix.package }} 0) 
          echo ::set-output name=uri::$(node ./scripts/release/getPackageData.js ${{ matrix.package }} 1)

      # Setup Pinata
      - name: Setup Pinata
        run: pinata-cli -a ${{ secrets.PINATA_API_KEY }}

      # Fetch Built Wrappers
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: ci.yml
          workflow_conclusion: success
          branch: main
          event: push
          name: ${{ steps.package.outputs.name }}-build-artifact
          path: ./${{ steps.package.outputs.name }}
      - name: create deployments
        run: mkdir ./deployments # fails if dir already exists but that's okay
        continue-on-error: true

      # Deploy wrappers to IPFS
      - name: Deploy current wrapper to IPFS
        run: pinata-cli -u ./${{ steps.package.outputs.name }} > ./deployments/${{ steps.package.outputs.name }}.ipfs.txt
      - id: ipfs
        name: Fetch IPFS CID for current wrapper
        run: echo ::set-output name=value::$(node ./scripts/release/getIpfsCid.js "$(cat ./deployments/${{ steps.package.outputs.name }}.ipfs.txt)")

      # Deploy wrappers to ENS
      - id: ensExists
        name: Check if ens uri exists
        run: 'echo ::set-output name=value::$(node ./scripts/release/checkEnsExists.js "$(ethers-ens lookup ${{ steps.package.outputs.uri }} --rpc https://rinkeby.infura.io/v3/${{ secrets.INFURA_KEY }})")'

      - name: Create ens uri
        uses: Wandalen/wretry.action@v1.0.11
        with:
          command: ethers-ens set-subnode "${{ steps.package.outputs.uri }}" --account ${{ secrets.PRIVATE_KEY }} --rpc https://rinkeby.infura.io/v3/${{ secrets.INFURA_KEY }} --yes --wait
          attempt_limit: 3
          attempt_delay: 5000
        if: ${{ (steps.ensExists.outputs.value == 'false') }}

      - name: Publish current wrapper to ENS
        uses: Wandalen/wretry.action@v1.0.11
        with:
          command: "ethers-ens set-content ${{ steps.package.outputs.uri }} ${{ steps.ipfs.outputs.value }} --account ${{ secrets.PRIVATE_KEY }} --rpc https://rinkeby.infura.io/v3/${{ secrets.INFURA_KEY }} --yes --wait"
          attempt_limit: 3
          attempt_delay: 5000
